# rabbitmq.conf for local dev
# Disable OAuth2 for local simulation because it requires HTTPS for the issuer
auth_backends.1 = rabbit_auth_backend_oauth2
auth_backends.2 = rabbit_auth_backend_internal

# Default credentials for local test
default_user = guest
default_pass = guest
